language: r
cache: packages

before_install:
  - echo $TRAVIS_R_VERSION_STRING
  # ImageMagick
  # - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:opencpu/imagemagick; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y libmagick++-dev; fi
  # Rmpfr
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt install -qq libmpfr-dev; fi
  # Java
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then R CMD javareconf; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then R --quiet -e 'install.packages("rJava", type="source", repos="http://cran.us.r-project.org")'; fi

after_script:
  # Install BEAST2
  - Rscript -e "beastier::install_beast2()"
  # Delete all previous results
  - rm result.png
  # Go!
  - travis_wait 60 Rscript example_1.R
  # Check if all files are created
  - if [ ! -f result.png ]; then echo "file 'result.png' not found" ; exit 1 ; fi

after_failure:
  # Download thesis
  - Rscript -e 'download.file("https://www.rug.nl/research/portal/files/132028374/Complete_thesis.pdf", tempfile())'

after_success:
  # Download thesis
  - Rscript -e 'download.file("https://www.rug.nl/research/portal/files/132028374/Complete_thesis.pdf", tempfile())'

