# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
  pull_request:

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - name: Install libcurl4-openssl-dev
        run: sudo apt install -qq libcurl4-openssl-dev

      - name: Install libgit2-dev
        run: sudo apt install -qq libgit2-dev

      - name: Fix rJava error # from https://travis-ci.community/t/cannot-connect-to-java-from-r/9754/8
        run: sudo $(which R) CMD javareconf

      - name: Install from GitHub master branches
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
          remotes::install_github("ropensci/beautier")
          remotes::install_github("ropensci/tracerer")
          remotes::install_github("ropensci/beastier")
          remotes::install_github("ropensci/mauricer")
          remotes::install_github("ropensci/babette")
        shell: Rscript {0}

      - name: Install BEAST2 from GitHub master branches
        run: beastier::install_beast2()
        shell: Rscript {0}

      - name: Run script with GitHub master branches
        run: Rscript example_1.R

      - name: Report with GitHub master branches
        run: beastier::beastier_report()
        shell: Rscript {0}

